# Generated by Django 4.2.3 on 2023-07-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_superadmin_account_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superuser',
            new_name='is_superadmin',
        ),
    ]
